name: Dinar
description: Money Management app.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_gradient_text: ^1.0.1
  flutter_bloc: ^8.1.6
  sqflite: ^2.3.3+1
  flutter_svg: ^2.0.10+1
  easy_localization: ^3.0.7
  get_it: ^8.0.0
  hexcolor: ^3.0.1
  fl_chart: ^0.69.0
  flutter_inner_shadow: ^0.0.1
  google_fonts: ^6.2.1
  dartz: ^0.10.1
  bloc: ^8.1.4
  meta: ^1.15.0
  shared_preferences: ^2.3.2
  app_links: ^6.3.2
  uuid: ^4.5.1
  shimmer: ^3.0.0
  loader_overlay: ^4.0.2+1
  equatable: ^2.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
