name: core
description: core folder
version: 0.1.0
publish_to: "none"

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  hexcolor: ^3.0.1
  flutter_inner_shadow: ^0.0.1
  fl_chart: ^0.69.0

dev_dependencies:
  test: null
