// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBOtZ7z5oWARgqzkcOG5xiMcftQhRdqIB0',
//     appId: '1:260346849661:android:255ed28595936a9a6cc414',
//     messagingSenderId: '260346849661',
//     projectId: 'saleem-habits',
//     storageBucket: 'saleem-habits.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyB-We-FdUBwohlZe22hPzxNG5SUjNPGA6M',
//     appId: '1:260346849661:ios:c61a1fcdca0704f36cc414',
//     messagingSenderId: '260346849661',
//     projectId: 'saleem-habits',
//     storageBucket: 'saleem-habits.appspot.com',
//     androidClientId: '260346849661-o7gse7cnqaelfhb0cvk2i63lphmpubi3.apps.googleusercontent.com',
//     iosClientId: '260346849661-6k056nqvea6rb1r8sre9pdag40iotk5n.apps.googleusercontent.com',
//     iosBundleId: 'solutions.ejad.saleem',
//   );
// }
