// import 'package:easy_localization/easy_localization.dart';
// import 'package:flutter/material.dart';
//
// import './saleem_icons.dart';
// import '../../features/categories/domain/entities/category.dart';
// import '../../features/habits/domain/entities/habit.dart';
// import '../../features/habits/domain/entities/note.dart';
// import '../../features/periods/domain/entities/period.dart';
// import '../localization/keys.g.dart';
// import '../utils/date_utils.dart';
//
// List<Period> get defaultPeriods => [
//       Period(
//         name: LocaleKeys.settings_any_time_period.tr(),
//         start: null,
//         end: null,
//         order: 0,
//         backgroundImage: "morning",
//       ),
//       Period(
//         name: LocaleKeys.settings_morning_period.tr(),
//         start: TimeOfDay(hour: 6, minute: 0),
//         end: TimeOfDay(hour: 8, minute: 0),
//         order: 1,
//         backgroundImage: "morning",
//       ),
//       Period(
//         name: LocaleKeys.settings_evening_period.tr(),
//         start: TimeOfDay(hour: 20, minute: 0),
//         end: TimeOfDay(hour: 22, minute: 0),
//         order: 2,
//         backgroundImage: "night",
//       ),
//     ];
//
// List<Category> get defaultCategories => [
//       Category(
//         name: LocaleKeys.settings_health_category.tr(),
//         order: 0,
//         color: Colors.blue,
//       ),
//       Category(
//         name: LocaleKeys.settings_skills_category.tr(),
//         order: 1,
//         color: Colors.red,
//       ),
//     ];
//
// List<Habit> get library => [
//       Habit(
//         name: LocaleKeys.library_1.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: -30,
//         consecutive: true,
//         icon: Saleem.ramadan_sunrise,
//         interval: "D",
//         amount: 1,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_1d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_2.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 0,
//         consecutive: false,
//         icon: Saleem.alarm_clock,
//         interval: "D01236",
//         amount: 1,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_2d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_3.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 0,
//         consecutive: false,
//         icon: Saleem.exercise_3,
//         interval: "D26",
//         amount: 30,
//         unit: LocaleKeys.edit_minute.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_3d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_4.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 0,
//         consecutive: false,
//         icon: Saleem.water_3,
//         interval: "D",
//         amount: 10,
//         unit: LocaleKeys.edit_glass.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_4d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_5.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 0,
//         consecutive: false,
//         icon: Saleem.no_smoking_2,
//         interval: "D",
//         amount: 1,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_5d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_6.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 0,
//         consecutive: false,
//         icon: Saleem.social_media,
//         interval: "D",
//         amount: 1,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_6d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_7.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 60,
//         consecutive: false,
//         icon: Saleem.video_call,
//         interval: "D",
//         amount: 1,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_7d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_8.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 30,
//         consecutive: false,
//         icon: Saleem.drink,
//         interval: "D",
//         amount: 1,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_8d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_9.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 0,
//         consecutive: false,
//         icon: Saleem.food,
//         interval: "D",
//         amount: 2,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_9d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_10.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 0,
//         consecutive: false,
//         icon: Saleem.sugar,
//         interval: "D",
//         amount: 1,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_10d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_11.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 0,
//         consecutive: false,
//         icon: Saleem.grandfather,
//         interval: "W",
//         amount: 1,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_11d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_12.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 0,
//         consecutive: false,
//         icon: Saleem.family_car,
//         interval: "W",
//         amount: 2,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_12d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_13.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 0,
//         consecutive: false,
//         icon: Saleem.smartphone_2,
//         interval: "D",
//         amount: 1,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_13d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_14.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 20,
//         consecutive: false,
//         icon: Saleem.quran,
//         interval: "A",
//         amount: 1,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_14d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_15.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 0,
//         consecutive: false,
//         icon: Saleem.quran_2,
//         interval: "M",
//         amount: 1,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_15d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_16.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 365,
//         consecutive: false,
//         icon: Saleem.islamic_prayer,
//         interval: "A",
//         amount: 1,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_16d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_17.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 0,
//         consecutive: false,
//         icon: Saleem.no_food,
//         interval: "D03",
//         amount: 1,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_17d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_18.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 10,
//         consecutive: false,
//         icon: Saleem.fasting,
//         interval: "A",
//         amount: 1,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_18d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_19.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 200,
//         consecutive: false,
//         icon: Saleem.book,
//         interval: "D",
//         amount: 10,
//         unit: LocaleKeys.edit_page.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_19d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_20.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 0,
//         consecutive: false,
//         icon: Saleem.quran_4,
//         interval: "D4",
//         amount: 1,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_20d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_21.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 0,
//         consecutive: false,
//         icon: Saleem.tasbih,
//         interval: "D",
//         amount: 1000,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_21d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_22.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 0,
//         consecutive: false,
//         icon: Saleem.prayer_beads,
//         interval: "D",
//         amount: 100,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_22d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_23.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 0,
//         consecutive: false,
//         icon: Saleem.water_2,
//         interval: "D",
//         amount: 1,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_23d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_24.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 0,
//         consecutive: false,
//         icon: Saleem.quran_rehal,
//         interval: "D",
//         amount: 5,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_24d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//       Habit(
//         name: LocaleKeys.library_25.tr(),
//         periodId: 1,
//         categoryId: 0,
//         startDate: dateNow,
//         goal: 0,
//         consecutive: false,
//         icon: Saleem.adhan_call,
//         interval: "D",
//         amount: 3,
//         unit: LocaleKeys.edit_time.tr(),
//         notification: null,
//         notes: [
//           Note(
//             content: LocaleKeys.library_25d.tr(),
//             date: DateTime.now(),
//           ),
//         ],
//       ),
//     ];
