// /// Flutter icons Saleem
// /// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
// /// This font was generated by FlutterIcon.com, which is derived from Fontello.
// import 'package:flutter/widgets.dart';
//
// class Saleem {
//   Saleem._();
//
//   static const _kFontFam = 'Saleem';
//   static const String? _kFontPkg = null;
//
//   static const IconData action_camera =
//       IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData adhan_call =
//       IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData advice = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData alarm_clock =
//       IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData american_football =
//       IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ancestry = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData apple = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData apple_2 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData arabian_lantern =
//       IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData arabian_magic_lamp =
//       IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData arabic_lamp =
//       IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData archery = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData archery_1 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData arm_wrestling =
//       IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData armband = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData asr = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData award = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData baby = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bag = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData baking_tray =
//       IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData baking = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ballet = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bandage = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bar = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData barbecue = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData barbell = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData baseball = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData baseball_2 =
//       IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData baseball_1 =
//       IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData baseball_3 =
//       IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData basketball =
//       IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData basketball_2 =
//       IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData basketball_1 =
//       IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData basketball_3 =
//       IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bat = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData beard = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bedug = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData biceps = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bicycle = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bicycle_2 = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData birthday_cake =
//       IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData blender = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData board_game =
//       IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData board = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bonsai = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData book = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bottle = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bowling = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData boxing = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData boxing_2 = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bowling_2 = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData boxing_gloves =
//       IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bra = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData brain = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData brainstorm =
//       IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData bread = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData browser = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData buck = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData budget = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData building_plan =
//       IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cabinet = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cactus = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cactus_2 = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData calculator =
//       IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData calendar = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData calendar_2 =
//       IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData calendar_3 =
//       IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData calories_calculator =
//       IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData camel_facing_left =
//       IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData camera = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData camper_van =
//       IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData camping = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData candle = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData candy = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cannon = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cap = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData card_game = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData card_game_2 =
//       IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cardio = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData care = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData carrot = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cat_food = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cat = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData certificate =
//       IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData chess = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData chess_2 = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cholesterol =
//       IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cholesterol_2 =
//       IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData chronometer =
//       IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData chronometer_2 =
//       IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cinema = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cinema_2 = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cleaning = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData climber = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData clipboard = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData coaching = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData coaching_2 =
//       IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData coffee = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData clock_2 = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData controller =
//       IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cooking_pot =
//       IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cooking_pot_2 =
//       IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cooking = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cooking_2 = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData couple = IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData cricket_bat =
//       IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData daily_health_app =
//       IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData dairy_products =
//       IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData dart_board =
//       IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData dates = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData daughter = IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData decision_making =
//       IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData desk = IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData dhuhr = IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData diet = IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData diet_2 = IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData diet_3 = IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData diet_4 = IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData diet_5 = IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData diet_6 = IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData diet_7 = IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData dinner = IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData direction = IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData diving_goggles =
//       IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData doctor = IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData domino = IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData donation = IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData donation_2 =
//       IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData dough_rolling =
//       IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData drink = IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData drink_2 = IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData drum = IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData dumbbell = IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData dumbbell_2 =
//       IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData dumbbell_1 =
//       IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData education = IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData egg = IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData elearning = IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData excellence =
//       IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData exercise = IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData exercise_2 =
//       IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData exercise_3 =
//       IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData experience =
//       IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData eyd_drum = IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData eyd_gun = IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData facial_mask =
//       IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData fajr = IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData family_book =
//       IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData family_car =
//       IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData fast_food = IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData fasting = IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData father = IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData fencing = IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData fireplace = IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData fish_tank = IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData fish = IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData fish_2 = IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData fishing_rod =
//       IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData fishing_rod_2 =
//       IconData(0xe89f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData fishing = IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData flower_pot =
//       IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData focus = IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData focus_2 = IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData food_app = IconData(0xe8a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData food = IconData(0xe8a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData football = IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData football_1 =
//       IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData forbidden_foods =
//       IconData(0xe8a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData french_fries =
//       IconData(0xe8a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData fruit = IconData(0xe8aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData fruit_2 = IconData(0xe8ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData garden = IconData(0xe8ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData gardening = IconData(0xe8ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData gift_box = IconData(0xe8ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData gloves = IconData(0xe8af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData gloves_2 = IconData(0xe8b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData goal = IconData(0xe8b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData goal_2 = IconData(0xe8b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData goal_1 = IconData(0xe8b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData golf = IconData(0xe8b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData golf_2 = IconData(0xe8b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData golf_1 = IconData(0xe8b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData gps = IconData(0xe8b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData grandfather =
//       IconData(0xe8b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData grandmother =
//       IconData(0xe8b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData grill = IconData(0xe8ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData growth = IconData(0xe8bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData growth_2 = IconData(0xe8bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData growth_3 = IconData(0xe8bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData guitar = IconData(0xe8be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData gym_equipment =
//       IconData(0xe8bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData gym_equipment_2 =
//       IconData(0xe8c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData gym = IconData(0xe8c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData gym_2 = IconData(0xe8c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData gym_1 = IconData(0xe8c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData gymnastic_rings =
//       IconData(0xe8c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData gymnastic_rings_2 =
//       IconData(0xe8c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData gymnastics =
//       IconData(0xe8c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData gymnastics_2 =
//       IconData(0xe8c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData hajj = IconData(0xe8c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData halal = IconData(0xe8ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData hammock = IconData(0xe8cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData hamsa_hand =
//       IconData(0xe8cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData hand_grip = IconData(0xe8cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData handbag = IconData(0xe8ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData hand_grip_1 =
//       IconData(0xe8cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData hat = IconData(0xe8d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData headphones =
//       IconData(0xe8d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData headphones_2 =
//       IconData(0xe8d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData healthy_food =
//       IconData(0xe8d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData healthy_heart =
//       IconData(0xe8d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData heart_rate =
//       IconData(0xe8d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData heart_rate_2 =
//       IconData(0xe8d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData heart = IconData(0xe8d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData heart_2 = IconData(0xe8d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData heartbeat = IconData(0xe8d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData helmet = IconData(0xe8da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData hijab = IconData(0xe8db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData hijab_veil =
//       IconData(0xe8dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData hiking = IconData(0xe8dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData hiking_2 = IconData(0xe8de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData hockey = IconData(0xe8df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData home_insurance =
//       IconData(0xe8e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData home = IconData(0xe8e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData homework = IconData(0xe8e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData horse = IconData(0xe8e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData house_key = IconData(0xe8e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ice_skate = IconData(0xe8e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ice_skates =
//       IconData(0xe8e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData idea = IconData(0xe8e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData iftar = IconData(0xe8e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData incense = IconData(0xe8e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData iron = IconData(0xe8ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData isha = IconData(0xe8eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData isha_prayer =
//       IconData(0xe8ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData islamic_friday_prayer =
//       IconData(0xe8ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData islamic_ghusl =
//       IconData(0xe8ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData islamic_halal =
//       IconData(0xe8ef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData islamic_minbar =
//       IconData(0xe8f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData islamic_mosque =
//       IconData(0xe8f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData islamic_pray =
//       IconData(0xe8f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData islamic_prayer =
//       IconData(0xe8f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData islamic_ramadan =
//       IconData(0xe8f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData islamic_wudu =
//       IconData(0xe8f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData isotonic = IconData(0xe8f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData jogging = IconData(0xe8f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData juice = IconData(0xe8f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData juicer = IconData(0xe8f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData jump_rope = IconData(0xe8fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData jump_rope_2 =
//       IconData(0xe8fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData kaaba = IconData(0xe8fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData kaaba_2 = IconData(0xe8fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData kaaba_building =
//       IconData(0xe8fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData karate = IconData(0xe8ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData kayak = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData kettlebell =
//       IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData key_person =
//       IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData kite = IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData knitting = IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData knitting_2 =
//       IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData kufi = IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData kufi_2 = IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData lantern = IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData lantern_2 = IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData laptop = IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData learning = IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData list = IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData listening = IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData locker = IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData luggage = IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData maghrib = IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData maghrib_prayer =
//       IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData make_up = IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData man = IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData maze = IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData meal = IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData meal_2 = IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData measure_tape =
//       IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData measure = IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData meat = IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData medal = IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData megaphone = IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData microphone =
//       IconData(0xe91d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData moon = IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData moslem = IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData mosque = IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData mosque_2 = IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData mosque_3 = IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData mother = IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData motivation =
//       IconData(0xe924, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData motivation_2 =
//       IconData(0xe925, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData mug = IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData mug_2 = IconData(0xe927, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData mukenah = IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData muscle = IconData(0xe929, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData muscle_2 = IconData(0xe92a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData muscle_3 = IconData(0xe92b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData muslim = IconData(0xe92c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData muslim_2 = IconData(0xe92d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData muslim_3 = IconData(0xe92e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData muslim_4 = IconData(0xe92f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData muslimah = IconData(0xe930, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData muslim_man =
//       IconData(0xe931, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData muslim_man_praying =
//       IconData(0xe932, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData muslim_praying =
//       IconData(0xe933, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData muslim_praying_hands =
//       IconData(0xe934, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData muslim_woman_praying =
//       IconData(0xe935, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData nature = IconData(0xe936, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData newspaper = IconData(0xe937, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData niqab = IconData(0xe938, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData no_alcohol =
//       IconData(0xe939, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData no_alcohol_2 =
//       IconData(0xe93a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData no_drink = IconData(0xe93b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData no_drink_2 =
//       IconData(0xe93c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData no_food = IconData(0xe93d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData no_isbal = IconData(0xe93e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData no_junk_food =
//       IconData(0xe93f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData no_music = IconData(0xe940, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData no_pig = IconData(0xe941, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData no_smoking =
//       IconData(0xe942, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData no_smoking_2 =
//       IconData(0xe943, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData oats = IconData(0xe944, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData old_oil_lamp =
//       IconData(0xe945, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData open_book = IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData origami = IconData(0xe947, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData origami_2 = IconData(0xe948, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData painting = IconData(0xe949, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData paper_cup = IconData(0xe94a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData pet_care = IconData(0xe94b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData pet_house = IconData(0xe94c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData photo_album =
//       IconData(0xe94d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData photo_camera =
//       IconData(0xe94e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData photo_frame =
//       IconData(0xe94f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData piano = IconData(0xe950, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData piggy_bank =
//       IconData(0xe951, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData pills = IconData(0xe952, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData pills_2 = IconData(0xe953, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ping_pong = IconData(0xe954, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ping_pong_1 =
//       IconData(0xe955, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData plant_pot = IconData(0xe956, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData plant = IconData(0xe957, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData plant_2 = IconData(0xe958, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData planting = IconData(0xe959, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData playing_cards =
//       IconData(0xe95a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData pool = IconData(0xe95b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData post_stamp =
//       IconData(0xe95c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData pottery = IconData(0xe95d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData prayer = IconData(0xe95e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData prayer_beads =
//       IconData(0xe95f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData praying = IconData(0xe960, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData praying_2 = IconData(0xe961, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData presentation =
//       IconData(0xe962, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData protein_powder =
//       IconData(0xe963, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData protein = IconData(0xe964, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData protein_2 = IconData(0xe965, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData protein_1 = IconData(0xe966, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData punch_ball =
//       IconData(0xe967, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData punching_bag =
//       IconData(0xe968, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData purpose = IconData(0xe969, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData puzzle = IconData(0xe96a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData puzzle_2 = IconData(0xe96b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData qibla = IconData(0xe96c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData qibla_2 = IconData(0xe96d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData question = IconData(0xe96e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData question_2 =
//       IconData(0xe96f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData quran = IconData(0xe970, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData quran_2 = IconData(0xe971, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData quran_4 = IconData(0xe973, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData quran_book =
//       IconData(0xe974, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData quran_rehal =
//       IconData(0xe975, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData racket = IconData(0xe976, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData rafting = IconData(0xe977, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ramadan_crescent_moon =
//       IconData(0xe978, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ramadan_fasting =
//       IconData(0xe979, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ramadan_iftar =
//       IconData(0xe97a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ramadan_month =
//       IconData(0xe97b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ramadan_sunrise =
//       IconData(0xe97c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ramadn_azhar =
//       IconData(0xe97d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData raya_rosary =
//       IconData(0xe97e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData reading = IconData(0xe97f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData remote_control =
//       IconData(0xe980, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData role_model =
//       IconData(0xe981, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData roller_skate =
//       IconData(0xe982, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData roller_skate_1 =
//       IconData(0xe983, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData rope = IconData(0xe984, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData routine = IconData(0xe985, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData rowboat = IconData(0xe986, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData rub_el_hizb =
//       IconData(0xe987, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData rub_el_hizb_1 =
//       IconData(0xe988, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData rugby = IconData(0xe989, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData rugs = IconData(0xe98a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ruku_2 = IconData(0xe98c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ruku_posture =
//       IconData(0xe98d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData running_man =
//       IconData(0xe98e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData rythmic_gymnastics =
//       IconData(0xe98f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sadaqah = IconData(0xe990, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sailing = IconData(0xe991, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sajadah = IconData(0xe992, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData salad = IconData(0xe993, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData scale = IconData(0xe994, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData scale_2 = IconData(0xe995, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData scale_3 = IconData(0xe996, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData scales = IconData(0xe997, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData schedule = IconData(0xe998, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData schedule_2 =
//       IconData(0xe999, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData schedule_3 =
//       IconData(0xe99a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData scrapbook = IconData(0xe99b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sermon = IconData(0xe99c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sewing = IconData(0xe99d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData shalat = IconData(0xe99e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData shoes = IconData(0xe99f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData shopping_bag =
//       IconData(0xe9a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData shopping = IconData(0xe9a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData shopping_2 =
//       IconData(0xe9a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData short = IconData(0xe9a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData shower = IconData(0xe9a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData shrine = IconData(0xe9a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData shuttlecock =
//       IconData(0xe9a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData singing = IconData(0xe9a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData skateboard =
//       IconData(0xe9a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData skateboard_2 =
//       IconData(0xe9a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData skill = IconData(0xe9aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData skin_care = IconData(0xe9ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData skipping_rope =
//       IconData(0xe9ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData skipping_rope_2 =
//       IconData(0xe9ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sleep = IconData(0xe9ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData small_mosque =
//       IconData(0xe9af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData smartphone =
//       IconData(0xe9b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData smartphone_2 =
//       IconData(0xe9b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData smartwatch =
//       IconData(0xe9b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData smartwatch_2 =
//       IconData(0xe9b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData smoothie = IconData(0xe9b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sneakers = IconData(0xe9b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData soccer_ball =
//       IconData(0xe9b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData social_media =
//       IconData(0xe9b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sock = IconData(0xe9b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sofa = IconData(0xe9ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData spinning = IconData(0xe9bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sport = IconData(0xe9bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sport_2 = IconData(0xe9bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData stamp_collecting =
//       IconData(0xe9be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData star_and_crescent_moon =
//       IconData(0xe9bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData step = IconData(0xe9c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData stopwatch = IconData(0xe9c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData strategy = IconData(0xe9c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData stroller = IconData(0xe9c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData strong = IconData(0xe9c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData struggle = IconData(0xe9c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData student = IconData(0xe9c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData study = IconData(0xe9c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData subah_prayer =
//       IconData(0xe9c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData success = IconData(0xe9c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData success_2 = IconData(0xe9ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData success_3 = IconData(0xe9cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sufi_mystic =
//       IconData(0xe9cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sugar = IconData(0xe9cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sujud = IconData(0xe9ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData sujud_posture =
//       IconData(0xe9cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData supplement =
//       IconData(0xe9d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData support = IconData(0xe9d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData surfboard = IconData(0xe9d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData suspension =
//       IconData(0xe9d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData swimming_pool =
//       IconData(0xe9d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData swimming_pool_2 =
//       IconData(0xe9d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData swimming = IconData(0xe9d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData swimming_2 =
//       IconData(0xe9d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData table_games =
//       IconData(0xe9d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData tape_measure =
//       IconData(0xe9da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData tape_measure_1 =
//       IconData(0xe9db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData tasbih = IconData(0xe9dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData tawheed = IconData(0xe9de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData tea = IconData(0xe9df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData tea_2 = IconData(0xe9e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData team = IconData(0xe9e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData team_2 = IconData(0xe9e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData telescope = IconData(0xe9e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData tennis_racket =
//       IconData(0xe9e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData tennis = IconData(0xe9e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData timetable = IconData(0xe9e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData to_do_list =
//       IconData(0xe9e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData toast = IconData(0xe9e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData tooth = IconData(0xe9e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData toothbrush =
//       IconData(0xe9ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData torso = IconData(0xe9eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData towel = IconData(0xe9ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData towel_2 = IconData(0xe9ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData training = IconData(0xe9ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData training_2 =
//       IconData(0xe9ef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData training_3 =
//       IconData(0xe9f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData traveling = IconData(0xe9f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData treadmill = IconData(0xe9f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData treadmill_2 =
//       IconData(0xe9f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData treadmill_3 =
//       IconData(0xe9f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData trust = IconData(0xe9f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData tutorial = IconData(0xe9f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData tv_screen = IconData(0xe9f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData tv_screen_2 =
//       IconData(0xe9f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData vegan_burger =
//       IconData(0xe9f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData vegetables =
//       IconData(0xe9fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData vegetables_2 =
//       IconData(0xe9fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData video_call =
//       IconData(0xe9fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData video_game =
//       IconData(0xe9fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData video_game_2 =
//       IconData(0xe9fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData vitamins = IconData(0xe9ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData vitamins_2 =
//       IconData(0xea00, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData vitamins_3 =
//       IconData(0xea01, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData volleyball =
//       IconData(0xea02, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData vr_glasses =
//       IconData(0xea03, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData washing_machine =
//       IconData(0xea04, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData watch = IconData(0xea05, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData water = IconData(0xea06, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData water_2 = IconData(0xea07, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData water_3 = IconData(0xea08, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData water_bottle =
//       IconData(0xea09, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData watermelon =
//       IconData(0xea0a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData wedding_cake =
//       IconData(0xea0b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData wedding_rings =
//       IconData(0xea0c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData weight_reduction =
//       IconData(0xea0d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData weight = IconData(0xea0e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData weightlift =
//       IconData(0xea0f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData weightlifting =
//       IconData(0xea10, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData weightlifting_2 =
//       IconData(0xea11, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData weightlifting_3 =
//       IconData(0xea12, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData wheat = IconData(0xea14, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData whistle = IconData(0xea15, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData whistle_2 = IconData(0xea16, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData win = IconData(0xea17, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData window = IconData(0xea18, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData woman = IconData(0xea19, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData woman_2 = IconData(0xea1a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData worker = IconData(0xea1b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData wudhu = IconData(0xea1c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData wudhu_2 = IconData(0xea1d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData yoga = IconData(0xea1e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData yoga_2 = IconData(0xea1f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData yoga_ball = IconData(0xea20, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData yoga_mat = IconData(0xea21, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData zakat = IconData(0xea22, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData zakat_2 = IconData(0xea23, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData zam_zam = IconData(0xea24, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData zuhar_prayer =
//       IconData(0xea25, fontFamily: _kFontFam, fontPackage: _kFontPkg);
// }
//
// const Map<String, IconData> icons = {
//   "action-camera": Saleem.action_camera,
//   "adhan-call": Saleem.adhan_call,
//   "advice": Saleem.advice,
//   "alarm-clock": Saleem.alarm_clock,
//   "american-football": Saleem.american_football,
//   "ancestry": Saleem.ancestry,
//   "apple": Saleem.apple,
//   "apple_2": Saleem.apple_2,
//   "arabian-lantern": Saleem.arabian_lantern,
//   "arabian-magic-lamp": Saleem.arabian_magic_lamp,
//   "arabic-lamp": Saleem.arabic_lamp,
//   "archery": Saleem.archery,
//   "archery-1": Saleem.archery_1,
//   "arm-wrestling": Saleem.arm_wrestling,
//   "armband": Saleem.armband,
//   "asr": Saleem.asr,
//   "award": Saleem.award,
//   "baby": Saleem.baby,
//   "bag": Saleem.bag,
//   "baking-tray": Saleem.baking_tray,
//   "baking": Saleem.baking,
//   "ballet": Saleem.ballet,
//   "bandage": Saleem.bandage,
//   "bar": Saleem.bar,
//   "barbecue": Saleem.barbecue,
//   "barbell": Saleem.barbell,
//   "baseball": Saleem.baseball,
//   "baseball_2": Saleem.baseball_2,
//   "baseball-1": Saleem.baseball_1,
//   "baseball-2": Saleem.baseball_2,
//   "basketball": Saleem.basketball,
//   "basketball_2": Saleem.basketball_2,
//   "basketball-1": Saleem.basketball_1,
//   "basketball-2": Saleem.basketball_2,
//   "bat": Saleem.bat,
//   "beard": Saleem.beard,
//   "bedug": Saleem.bedug,
//   "biceps": Saleem.biceps,
//   "bicycle": Saleem.bicycle,
//   "bicycle_2": Saleem.bicycle_2,
//   "birthday-cake": Saleem.birthday_cake,
//   "blender": Saleem.blender,
//   "board-game": Saleem.board_game,
//   "board": Saleem.board,
//   "bonsai": Saleem.bonsai,
//   "book": Saleem.book,
//   "bottle": Saleem.bottle,
//   "bowling": Saleem.bowling,
//   "boxing": Saleem.boxing,
//   "boxing_2": Saleem.boxing_2,
//   "bowling_2": Saleem.bowling_2,
//   "boxing-gloves": Saleem.boxing_gloves,
//   "bra": Saleem.bra,
//   "brain": Saleem.brain,
//   "brainstorm": Saleem.brainstorm,
//   "bread": Saleem.bread,
//   "browser": Saleem.browser,
//   "buck": Saleem.buck,
//   "budget": Saleem.budget,
//   "building-plan": Saleem.building_plan,
//   "cabinet": Saleem.cabinet,
//   "cactus": Saleem.cactus,
//   "cactus_2": Saleem.cactus_2,
//   "calculator": Saleem.calculator,
//   "calendar": Saleem.calendar,
//   "calendar_2": Saleem.calendar_2,
//   "calendar_3": Saleem.calendar_3,
//   "calories-calculator": Saleem.calories_calculator,
//   "camel-facing-left": Saleem.camel_facing_left,
//   "camera": Saleem.camera,
//   "camper-van": Saleem.camper_van,
//   "camping": Saleem.camping,
//   "candle": Saleem.candle,
//   "candy": Saleem.candy,
//   "cannon": Saleem.cannon,
//   "cap": Saleem.cap,
//   "card-game": Saleem.card_game,
//   "card-game_2": Saleem.card_game_2,
//   "cardio": Saleem.cardio,
//   "care": Saleem.care,
//   "carrot": Saleem.carrot,
//   "cat-food": Saleem.cat_food,
//   "cat": Saleem.cat,
//   "certificate": Saleem.certificate,
//   "chess": Saleem.chess,
//   "chess_2": Saleem.chess_2,
//   "cholesterol": Saleem.cholesterol,
//   "cholesterol_2": Saleem.cholesterol_2,
//   "chronometer": Saleem.chronometer,
//   "chronometer_2": Saleem.chronometer_2,
//   "cinema": Saleem.cinema,
//   "cinema_2": Saleem.cinema_2,
//   "cleaning": Saleem.cleaning,
//   "climber": Saleem.climber,
//   "clipboard": Saleem.clipboard,
//   "coaching": Saleem.coaching,
//   "coaching_2": Saleem.coaching_2,
//   "coffee": Saleem.coffee,
//   "clock_2": Saleem.clock_2,
//   "controller": Saleem.controller,
//   "cooking-pot": Saleem.cooking_pot,
//   "cooking-pot_2": Saleem.cooking_pot_2,
//   "cooking": Saleem.cooking,
//   "cooking_2": Saleem.cooking_2,
//   "couple": Saleem.couple,
//   "cricket-bat": Saleem.cricket_bat,
//   "daily-health-app": Saleem.daily_health_app,
//   "dairy-products": Saleem.dairy_products,
//   "dart-board": Saleem.dart_board,
//   "dates": Saleem.dates,
//   "daughter": Saleem.daughter,
//   "decision-making": Saleem.decision_making,
//   "desk": Saleem.desk,
//   "dhuhr": Saleem.dhuhr,
//   "diet": Saleem.diet,
//   "diet_2": Saleem.diet_2,
//   "diet_3": Saleem.diet_3,
//   "diet_4": Saleem.diet_4,
//   "diet_5": Saleem.diet_5,
//   "diet_6": Saleem.diet_6,
//   "diet_7": Saleem.diet_7,
//   "dinner": Saleem.dinner,
//   "direction": Saleem.direction,
//   "diving-goggles": Saleem.diving_goggles,
//   "doctor": Saleem.doctor,
//   "domino": Saleem.domino,
//   "donation": Saleem.donation,
//   "donation_2": Saleem.donation_2,
//   "dough-rolling": Saleem.dough_rolling,
//   "drink": Saleem.drink,
//   "drink_2": Saleem.drink_2,
//   "drum": Saleem.drum,
//   "dumbbell": Saleem.dumbbell,
//   "dumbbell_2": Saleem.dumbbell_2,
//   "dumbbell-1": Saleem.dumbbell_1,
//   "education": Saleem.education,
//   "egg": Saleem.egg,
//   "elearning": Saleem.elearning,
//   "excellence": Saleem.excellence,
//   "exercise": Saleem.exercise,
//   "exercise_2": Saleem.exercise_2,
//   "exercise_3": Saleem.exercise_3,
//   "experience": Saleem.experience,
//   "eyd-drum": Saleem.eyd_drum,
//   "eyd-gun": Saleem.eyd_gun,
//   "facial-mask": Saleem.facial_mask,
//   "fajr": Saleem.fajr,
//   "family-book": Saleem.family_book,
//   "family-car": Saleem.family_car,
//   "fast-food": Saleem.fast_food,
//   "fasting": Saleem.fasting,
//   "father": Saleem.father,
//   "fencing": Saleem.fencing,
//   "fireplace": Saleem.fireplace,
//   "fish-tank": Saleem.fish_tank,
//   "fish": Saleem.fish,
//   "fish_2": Saleem.fish_2,
//   "fishing-rod": Saleem.fishing_rod,
//   "fishing-rod_2": Saleem.fishing_rod_2,
//   "fishing": Saleem.fishing,
//   "flower-pot": Saleem.flower_pot,
//   "focus": Saleem.focus,
//   "focus_2": Saleem.focus_2,
//   "food-app": Saleem.food_app,
//   "food": Saleem.food,
//   "football": Saleem.football,
//   "football-1": Saleem.football_1,
//   "forbidden-foods": Saleem.forbidden_foods,
//   "french-fries": Saleem.french_fries,
//   "fruit": Saleem.fruit,
//   "fruit_2": Saleem.fruit_2,
//   "garden": Saleem.garden,
//   "gardening": Saleem.gardening,
//   "gift-box": Saleem.gift_box,
//   "gloves": Saleem.gloves,
//   "gloves_2": Saleem.gloves_2,
//   "goal": Saleem.goal,
//   "goal_2": Saleem.goal_2,
//   "goal-1": Saleem.goal_1,
//   "golf": Saleem.golf,
//   "golf_2": Saleem.golf_2,
//   "golf-1": Saleem.golf_1,
//   "gps": Saleem.gps,
//   "grandfather": Saleem.grandfather,
//   "grandmother": Saleem.grandmother,
//   "grill": Saleem.grill,
//   "growth": Saleem.growth,
//   "growth_2": Saleem.growth_2,
//   "growth_3": Saleem.growth_3,
//   "guitar": Saleem.guitar,
//   "gym-equipment": Saleem.gym_equipment,
//   "gym-equipment_2": Saleem.gym_equipment_2,
//   "gym": Saleem.gym,
//   "gym_2": Saleem.gym_2,
//   "gym-1": Saleem.gym_1,
//   "gymnastic-rings": Saleem.gymnastic_rings,
//   "gymnastic-rings_2": Saleem.gymnastic_rings_2,
//   "gymnastics": Saleem.gymnastics,
//   "gymnastics_2": Saleem.gymnastics_2,
//   "hajj": Saleem.hajj,
//   "halal": Saleem.halal,
//   "hammock": Saleem.hammock,
//   "hamsa-hand": Saleem.hamsa_hand,
//   "hand-grip": Saleem.hand_grip,
//   "handbag": Saleem.handbag,
//   "hand-grip-2": Saleem.hand_grip,
//   "hat": Saleem.hat,
//   "headphones": Saleem.headphones,
//   "headphones_2": Saleem.headphones_2,
//   "healthy-food": Saleem.healthy_food,
//   "healthy-heart": Saleem.healthy_heart,
//   "heart-rate": Saleem.heart_rate,
//   "heart": Saleem.heart,
//   "heart_2": Saleem.heart_2,
//   "heartbeat": Saleem.heartbeat,
//   "helmet": Saleem.helmet,
//   "hijab": Saleem.hijab,
//   "hijab-veil": Saleem.hijab_veil,
//   "hiking": Saleem.hiking,
//   "hiking_2": Saleem.hiking_2,
//   "hockey": Saleem.hockey,
//   "home-insurance": Saleem.home_insurance,
//   "home": Saleem.home,
//   "homework": Saleem.homework,
//   "horse": Saleem.horse,
//   "house-key": Saleem.house_key,
//   "ice-skate": Saleem.ice_skate,
//   "ice-skates": Saleem.ice_skates,
//   "idea": Saleem.idea,
//   "iftar": Saleem.iftar,
//   "incense": Saleem.incense,
//   "iron": Saleem.iron,
//   "isha": Saleem.isha,
//   "isha-prayer": Saleem.isha_prayer,
//   "islamic-friday-prayer": Saleem.islamic_friday_prayer,
//   "islamic-ghusl": Saleem.islamic_ghusl,
//   "islamic-halal": Saleem.islamic_halal,
//   "islamic-minbar": Saleem.islamic_minbar,
//   "islamic-mosque": Saleem.islamic_mosque,
//   "islamic-pray": Saleem.islamic_pray,
//   "islamic-prayer": Saleem.islamic_prayer,
//   "islamic-ramadan": Saleem.islamic_ramadan,
//   "islamic-wudu": Saleem.islamic_wudu,
//   "isotonic": Saleem.isotonic,
//   "jogging": Saleem.jogging,
//   "juice": Saleem.juice,
//   "juicer": Saleem.juicer,
//   "jump-rope": Saleem.jump_rope,
//   "jump-rope_2": Saleem.jump_rope_2,
//   "kaaba": Saleem.kaaba,
//   "kaaba_2": Saleem.kaaba_2,
//   "kaaba-building": Saleem.kaaba_building,
//   "karate": Saleem.karate,
//   "kayak": Saleem.kayak,
//   "kettlebell": Saleem.kettlebell,
//   "key-person": Saleem.key_person,
//   "kite": Saleem.kite,
//   "knitting": Saleem.knitting,
//   "knitting_2": Saleem.knitting_2,
//   "kufi": Saleem.kufi,
//   "kufi_2": Saleem.kufi_2,
//   "lantern": Saleem.lantern,
//   "lantern_2": Saleem.lantern_2,
//   "laptop": Saleem.laptop,
//   "learning": Saleem.learning,
//   "list": Saleem.list,
//   "listening": Saleem.listening,
//   "locker": Saleem.locker,
//   "luggage": Saleem.luggage,
//   "maghrib": Saleem.maghrib,
//   "maghrib-prayer": Saleem.maghrib_prayer,
//   "make-up": Saleem.make_up,
//   "man": Saleem.man,
//   "maze": Saleem.maze,
//   "meal": Saleem.meal,
//   "meal_2": Saleem.meal_2,
//   "measure-tape": Saleem.measure_tape,
//   "measure": Saleem.measure,
//   "meat": Saleem.meat,
//   "medal": Saleem.medal,
//   "megaphone": Saleem.megaphone,
//   "microphone": Saleem.microphone,
//   "moon": Saleem.moon,
//   "moslem": Saleem.moslem,
//   "mosque": Saleem.mosque,
//   "mosque_2": Saleem.mosque_2,
//   "mosque_3": Saleem.mosque_3,
//   "mother": Saleem.mother,
//   "motivation": Saleem.motivation,
//   "motivation_2": Saleem.motivation_2,
//   "mug": Saleem.mug,
//   "mug_2": Saleem.mug_2,
//   "mukenah": Saleem.mukenah,
//   "muscle": Saleem.muscle,
//   "muscle_2": Saleem.muscle_2,
//   "muscle_3": Saleem.muscle_3,
//   "muslim": Saleem.muslim,
//   "muslim_2": Saleem.muslim_2,
//   "muslim_3": Saleem.muslim_3,
//   "muslim_4": Saleem.muslim_4,
//   "muslimah": Saleem.muslimah,
//   "muslim-man": Saleem.muslim_man,
//   "muslim-man-praying": Saleem.muslim_man_praying,
//   "muslim-praying": Saleem.muslim_praying,
//   "muslim-praying-hands": Saleem.muslim_praying_hands,
//   "muslim-woman-praying": Saleem.muslim_woman_praying,
//   "nature": Saleem.nature,
//   "newspaper": Saleem.newspaper,
//   "niqab": Saleem.niqab,
//   "no-alcohol": Saleem.no_alcohol,
//   "no-alcohol_2": Saleem.no_alcohol_2,
//   "no-drink": Saleem.no_drink,
//   "no-drink_2": Saleem.no_drink_2,
//   "no-food": Saleem.no_food,
//   "no-isbal": Saleem.no_isbal,
//   "no-junk-food": Saleem.no_junk_food,
//   "no-music": Saleem.no_music,
//   "no-pig": Saleem.no_pig,
//   "no-smoking": Saleem.no_smoking,
//   "heart-rate_2": Saleem.heart_rate_2,
//   "no-smoking_2": Saleem.no_smoking_2,
//   "oats": Saleem.oats,
//   "old-oil-lamp": Saleem.old_oil_lamp,
//   "open-book": Saleem.open_book,
//   "origami": Saleem.origami,
//   "origami_2": Saleem.origami_2,
//   "painting": Saleem.painting,
//   "paper-cup": Saleem.paper_cup,
//   "pet-care": Saleem.pet_care,
//   "pet-house": Saleem.pet_house,
//   "photo-album": Saleem.photo_album,
//   "photo-camera": Saleem.photo_camera,
//   "photo-frame": Saleem.photo_frame,
//   "piano": Saleem.piano,
//   "piggy-bank": Saleem.piggy_bank,
//   "pills": Saleem.pills,
//   "pills_2": Saleem.pills_2,
//   "ping-pong": Saleem.ping_pong,
//   "ping-pong-2": Saleem.ping_pong,
//   "plant-pot": Saleem.plant_pot,
//   "plant": Saleem.plant,
//   "plant_2": Saleem.plant_2,
//   "planting": Saleem.planting,
//   "playing-cards": Saleem.playing_cards,
//   "pool": Saleem.pool,
//   "post-stamp": Saleem.post_stamp,
//   "pottery": Saleem.pottery,
//   "prayer": Saleem.prayer,
//   "prayer-beads": Saleem.prayer_beads,
//   "praying": Saleem.praying,
//   "praying_2": Saleem.praying_2,
//   "presentation": Saleem.presentation,
//   "protein-powder": Saleem.protein_powder,
//   "protein": Saleem.protein,
//   "protein_2": Saleem.protein_2,
//   "protein-1": Saleem.protein_1,
//   "punch-ball": Saleem.punch_ball,
//   "punching-bag": Saleem.punching_bag,
//   "purpose": Saleem.purpose,
//   "puzzle": Saleem.puzzle,
//   "puzzle_2": Saleem.puzzle_2,
//   "qibla": Saleem.qibla,
//   "qibla_2": Saleem.qibla_2,
//   "question": Saleem.question,
//   "question_2": Saleem.question_2,
//   "quran": Saleem.quran,
//   "quran_2": Saleem.quran_2,
//   "quran_4": Saleem.quran_4,
//   "quran-book": Saleem.quran_book,
//   "quran-rehal": Saleem.quran_rehal,
//   "racket": Saleem.racket,
//   "rafting": Saleem.rafting,
//   "ramadan-crescent-moon": Saleem.ramadan_crescent_moon,
//   "ramadan-fasting": Saleem.ramadan_fasting,
//   "ramadan-iftar": Saleem.ramadan_iftar,
//   "ramadan-month": Saleem.ramadan_month,
//   "ramadan-sunrise": Saleem.ramadan_sunrise,
//   "ramadn-azhar": Saleem.ramadn_azhar,
//   "raya-rosary": Saleem.raya_rosary,
//   "reading": Saleem.reading,
//   "remote-control": Saleem.remote_control,
//   "role-model": Saleem.role_model,
//   "roller-skate": Saleem.roller_skate,
//   "roller-skate-2": Saleem.roller_skate,
//   "rope": Saleem.rope,
//   "routine": Saleem.routine,
//   "rowboat": Saleem.rowboat,
//   "rub-el-hizb": Saleem.rub_el_hizb,
//   "rub-el-hizb-2": Saleem.rub_el_hizb,
//   "rugby": Saleem.rugby,
//   "rugs": Saleem.rugs,
//   "ruku_2": Saleem.ruku_2,
//   "ruku-posture": Saleem.ruku_posture,
//   "running-man": Saleem.running_man,
//   "rythmic-gymnastics": Saleem.rythmic_gymnastics,
//   "sadaqah": Saleem.sadaqah,
//   "sailing": Saleem.sailing,
//   "sajadah": Saleem.sajadah,
//   "salad": Saleem.salad,
//   "scale": Saleem.scale,
//   "scale_2": Saleem.scale_2,
//   "scale_3": Saleem.scale_3,
//   "scales": Saleem.scales,
//   "schedule": Saleem.schedule,
//   "schedule_2": Saleem.schedule_2,
//   "schedule_3": Saleem.schedule_3,
//   "scrapbook": Saleem.scrapbook,
//   "sermon": Saleem.sermon,
//   "sewing": Saleem.sewing,
//   "shalat": Saleem.shalat,
//   "shoes": Saleem.shoes,
//   "shopping-bag": Saleem.shopping_bag,
//   "shopping": Saleem.shopping,
//   "shopping_2": Saleem.shopping_2,
//   "short": Saleem.short,
//   "shower": Saleem.shower,
//   "shrine": Saleem.shrine,
//   "shuttlecock": Saleem.shuttlecock,
//   "singing": Saleem.singing,
//   "skateboard": Saleem.skateboard,
//   "skateboard_2": Saleem.skateboard_2,
//   "skill": Saleem.skill,
//   "skin-care": Saleem.skin_care,
//   "skipping-rope": Saleem.skipping_rope,
//   "skipping-rope_2": Saleem.skipping_rope_2,
//   "sleep": Saleem.sleep,
//   "small-mosque": Saleem.small_mosque,
//   "smartphone": Saleem.smartphone,
//   "smartphone_2": Saleem.smartphone_2,
//   "smartwatch": Saleem.smartwatch,
//   "smartwatch_2": Saleem.smartwatch_2,
//   "smoothie": Saleem.smoothie,
//   "sneakers": Saleem.sneakers,
//   "soccer-ball": Saleem.soccer_ball,
//   "social-media": Saleem.social_media,
//   "sock": Saleem.sock,
//   "sofa": Saleem.sofa,
//   "spinning": Saleem.spinning,
//   "sport": Saleem.sport,
//   "sport_2": Saleem.sport_2,
//   "stamp-collecting": Saleem.stamp_collecting,
//   "star-and-crescent-moon": Saleem.star_and_crescent_moon,
//   "step": Saleem.step,
//   "stopwatch": Saleem.stopwatch,
//   "strategy": Saleem.strategy,
//   "stroller": Saleem.stroller,
//   "strong": Saleem.strong,
//   "struggle": Saleem.struggle,
//   "student": Saleem.student,
//   "study": Saleem.study,
//   "subah-prayer": Saleem.subah_prayer,
//   "success": Saleem.success,
//   "success_2": Saleem.success_2,
//   "success_3": Saleem.success_3,
//   "sufi-mystic": Saleem.sufi_mystic,
//   "sugar": Saleem.sugar,
//   "sujud": Saleem.sujud,
//   "sujud-posture": Saleem.sujud_posture,
//   "supplement": Saleem.supplement,
//   "support": Saleem.support,
//   "surfboard": Saleem.surfboard,
//   "suspension": Saleem.suspension,
//   "swimming-pool": Saleem.swimming_pool,
//   "swimming-pool_2": Saleem.swimming_pool_2,
//   "swimming": Saleem.swimming,
//   "swimming_2": Saleem.swimming_2,
//   "table-games": Saleem.table_games,
//   "tape-measure": Saleem.tape_measure,
//   "tape-measure-2": Saleem.tape_measure,
//   "tasbih": Saleem.tasbih,
//   "tawheed": Saleem.tawheed,
//   "tea": Saleem.tea,
//   "tea_2": Saleem.tea_2,
//   "team": Saleem.team,
//   "team_2": Saleem.team_2,
//   "telescope": Saleem.telescope,
//   "tennis-racket": Saleem.tennis_racket,
//   "tennis": Saleem.tennis,
//   "timetable": Saleem.timetable,
//   "to-do-list": Saleem.to_do_list,
//   "toast": Saleem.toast,
//   "tooth": Saleem.tooth,
//   "toothbrush": Saleem.toothbrush,
//   "torso": Saleem.torso,
//   "towel": Saleem.towel,
//   "towel_2": Saleem.towel_2,
//   "training": Saleem.training,
//   "training_2": Saleem.training_2,
//   "training_3": Saleem.training_3,
//   "traveling": Saleem.traveling,
//   "treadmill": Saleem.treadmill,
//   "treadmill_2": Saleem.treadmill_2,
//   "treadmill_3": Saleem.treadmill_3,
//   "trust": Saleem.trust,
//   "tutorial": Saleem.tutorial,
//   "tv-screen": Saleem.tv_screen,
//   "tv-screen_2": Saleem.tv_screen_2,
//   "vegan-burger": Saleem.vegan_burger,
//   "vegetables": Saleem.vegetables,
//   "vegetables_2": Saleem.vegetables_2,
//   "video-call": Saleem.video_call,
//   "video-game": Saleem.video_game,
//   "video-game_2": Saleem.video_game_2,
//   "vitamins": Saleem.vitamins,
//   "vitamins_2": Saleem.vitamins_2,
//   "vitamins_3": Saleem.vitamins_3,
//   "volleyball": Saleem.volleyball,
//   "vr-glasses": Saleem.vr_glasses,
//   "washing-machine": Saleem.washing_machine,
//   "watch": Saleem.watch,
//   "water": Saleem.water,
//   "water_2": Saleem.water_2,
//   "water_3": Saleem.water_3,
//   "water-bottle": Saleem.water_bottle,
//   "watermelon": Saleem.watermelon,
//   "wedding-cake": Saleem.wedding_cake,
//   "wedding-rings": Saleem.wedding_rings,
//   "weight-reduction": Saleem.weight_reduction,
//   "weight": Saleem.weight,
//   "weightlift": Saleem.weightlift,
//   "weightlifting": Saleem.weightlifting,
//   "weightlifting_2": Saleem.weightlifting_2,
//   "weightlifting_3": Saleem.weightlifting_3,
//   "wheat": Saleem.wheat,
//   "whistle": Saleem.whistle,
//   "whistle_2": Saleem.whistle_2,
//   "win": Saleem.win,
//   "window": Saleem.window,
//   "woman": Saleem.woman,
//   "woman_2": Saleem.woman_2,
//   "worker": Saleem.worker,
//   "wudhu": Saleem.wudhu,
//   "wudhu_2": Saleem.wudhu_2,
//   "yoga": Saleem.yoga,
//   "yoga_2": Saleem.yoga_2,
//   "yoga-ball": Saleem.yoga_ball,
//   "yoga-mat": Saleem.yoga_mat,
//   "zakat": Saleem.zakat,
//   "zakat_2": Saleem.zakat_2,
//   "zam-zam": Saleem.zam_zam,
//   "zuhar-prayer": Saleem.zuhar_prayer,
// };
